# Generated by Django 4.1.4 on 2022-12-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_base_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='email',
        ),
        migrations.AlterField(
            model_name='base',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
